/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContinuousPadderEditor.java
 *
 * Created on 2009-10-26, 17:43:54
 */
package mr.go.sgfilter.vis.app;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JCheckBox;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.LineBorder;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

/**
 *
 * @author Rzeźnik
 */
public class ContinuousPadderEditor extends javax.swing.JPanel {

    private final ContinuousPadderBean bean;

    /** Creates new form ContinuousPadderEditor */
    public ContinuousPadderEditor() {
        this(null);
    }

    ContinuousPadderEditor(ContinuousPadderBean bean) {
        this.bean = bean;
        initComponents();
    }

    public ContinuousPadderBean getBean() {
        return bean;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        paddingLeftCheckBox = new JCheckBox();
        paddingRightCheckBox = new JCheckBox();
        ResourceMap resourceMap =
                Application.getInstance(mr.go.sgfilter.vis.app.Application.class).
                getContext().getResourceMap(ContinuousPadderEditor.class);
        setBorder(BorderFactory.createTitledBorder(new LineBorder(new Color(0, 0, 0), 1, true), resourceMap.getString("ContinuousPadderEditor.border.title"))); // NOI18N
        setName("ContinuousPadderEditor"); // NOI18N
        setPreferredSize(new Dimension(470, 100));

        paddingLeftCheckBox.setText(resourceMap.getString("paddingLeftCheckBox.text")); // NOI18N
        paddingLeftCheckBox.setName("paddingLeftCheckBox"); // NOI18N

        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${bean.paddingLeft}"), paddingLeftCheckBox, BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        paddingRightCheckBox.setText(resourceMap.getString("paddingRightCheckBox.text")); // NOI18N
        paddingRightCheckBox.setName("paddingRightCheckBox"); // NOI18N

        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${bean.paddingRight}"), paddingRightCheckBox, BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(paddingRightCheckBox)
                    .addComponent(paddingLeftCheckBox))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paddingLeftCheckBox)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(paddingRightCheckBox)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JCheckBox paddingLeftCheckBox;
    private JCheckBox paddingRightCheckBox;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
