/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RamerDouglasPeuckerEditor.java
 *
 * Created on 2009-10-26, 17:49:33
 */
package mr.go.sgfilter.vis.app;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JSpinner.NumberEditor;
import javax.swing.SpinnerNumberModel;
import javax.swing.border.LineBorder;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

/**
 *
 * @author Rzeźnik
 */
public class RamerDouglasPeuckerEditor extends javax.swing.JPanel {

    private final RDPBean bean;

    /** Creates new form RamerDouglasPeuckerEditor */
    public RamerDouglasPeuckerEditor() {
        this(null);
    }

    public RamerDouglasPeuckerEditor(RDPBean bean) {
        this.bean = bean;
        initComponents();
    }

    public RDPBean getBean() {
        return bean;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();
        JLabel epsilonLabel = new JLabel();
        epsilonSpinner = new JSpinner();
        ResourceMap resourceMap =
                Application.getInstance(mr.go.sgfilter.vis.app.Application.class).
                getContext().getResourceMap(RamerDouglasPeuckerEditor.class);
        setBorder(BorderFactory.createTitledBorder(new LineBorder(new Color(0, 0, 0), 1, true), resourceMap.getString("RamerDouglasPeuckerEditor.border.title"))); // NOI18N
        setName("RamerDouglasPeuckerEditor"); // NOI18N
        setPreferredSize(new Dimension(470, 100));

        epsilonLabel.setText(resourceMap.getString("epsilonLabel.text")); // NOI18N
        epsilonLabel.setName("epsilonLabel"); // NOI18N

        epsilonSpinner.setModel(new SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        epsilonSpinner.setEditor(new NumberEditor(epsilonSpinner, "0.##"));
        epsilonSpinner.setName("epsilonSpinner"); // NOI18N

        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${bean.epsilon}"), epsilonSpinner, BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(epsilonLabel)
                .addGap(18, 18, 18)
                .addComponent(epsilonSpinner, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(epsilonLabel)
                    .addComponent(epsilonSpinner, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JSpinner epsilonSpinner;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
